version: "1"
services:
  - type: web
    name: student-info-service
    runtime: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"